cherry-picked: Added DEB init script and modified

diff --git a/stratio-ingestion-dist/src/main/unix/files_and_dirs/etc/init.d/ingestion-deb b/stratio-ingestion-dist/src/main/unix/files_and_dirs/etc/init.d/ingestion-deb
--- a/stratio-ingestion-dist/src/main/unix/files_and_dirs/etc/init.d/ingestion-deb
+++ b/stratio-ingestion-dist/src/main/unix/files_and_dirs/etc/init.d/ingestion-deb
@@ -1,3 +1,4 @@
+<<<<<<< HEAD
 #!/bin/bash 
 #
 #   /etc/rc.d/init.d/ingestion-skeleton
@@ -5,16 +6,20 @@
 #   Ingestion skeleton service
 #   
 # chkconfig: 2345 55 25
+=======
+#!/bin/bash
+>>>>>>> d83d831... Added DEB init script and modified
 ### BEGIN INIT INFO
-# Provides:          ingestion-skeleton
-# Required-Start:    $network $remote_fs $named
-# Required-Stop:     $network $remote_fs $named
+# Provides:          ingestion
+# Required-Start:    $network $remote_fs $syslog
+# Required-Stop:     $network $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Starts ingestion
 # Description:       Starts ingestion
 ### END INIT INFO
 
+<<<<<<< HEAD
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 INIT_HOME=`cd "${DIR}/.." >/dev/null; pwd`
 
@@ -50,184 +55,128 @@ DAEMON="$DIR/bin/ingestion.sh"
 
 MAX_TRIES=20
 SLEEP_TIME=3
+=======
+# Only configuration needed here
+FLUME_NAME=$(basename $0 | cut -d '-' -f2)
+NAME="ingestion-$FLUME_NAME"
+DESC="Ingestion ($FLUME_NAME)"
+>>>>>>> d83d831... Added DEB init script and modified
 
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+VARIABLES="/etc/default/ingestion-variables"
+FUNCTIONS="/etc/default/ingestion-functions"
 
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
+# Read default configuration variable file if it is present
+[ -r $DEFAULT ] && . $DEFAULT
 
-# Source function library.
-. /etc/rc.d/init.d/functions
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
 
+<<<<<<< HEAD
 
 
 # Function that validates the service
 function validateService(){
     :
 }
+=======
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+>>>>>>> d83d831... Added DEB init script and modified
 
-# Function that validates the service is able to start
-function validateStart(){
-    if [ ! -e "$CONF_FILE" ]; then
-        echo "Will NOT start: config file $CONF_FILE not found!"
-        exit 1
-    fi
-    checkDependencies solve_dependencies exit_on_fail || exit 1
-}
+# Source service configuration
+if [ -r $VARIABLES ]; then
+    . $VARIABLES
+fi
 
-# Function that validates the service is able to restart
-function validateRestart(){
-    :
-}
+# Load service configuration
+source $SERVICE_CONF
 
-# Function that validates the service is able to stop
-function validateStop(){
-    :
-}
-
-# Check wether this ports are up or not
-function checkPort(){
-    local port=$1
-    if ! (echo > /dev/tcp/0.0.0.0/$port) >/dev/null 2>&1; then
-        return 1
-    else
-        return 0
-    fi
-}
+# Get ingestion configuration for $FLUME_NAME instance
+CONF_FILE="$CONF/${CONF_FILES[$FLUME_NAME]}"
+DEPENDENCIES="${PORTS_DEPS[$FLUME_NAME]}"
 
 # Source check functions & validate service configuration
-validateService
+. $FUNCTIONS && validateService
 
-function start() {
+#
+# Function that starts the daemon/service
+#
+do_start(){
     validateStart
-    if [ -n "$INDENT_LEVEL" ]; then
-        echo -n "${SPACES}      > Starting $NAME: "
-    else
-        echo -n "Starting $NAME: "
-    fi
-    if getStatus > /dev/null 2>&1; then
-        echo -n "already running"
-    fi
-    daemon --user $USER --pidfile $PIDFILE "$DAEMON $DAEMON_OPTS"
-    echo
-    touch $LOCKFILE
-}   
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    start-stop-daemon --start --user $USER -c $USER --pidfile $PIDFILE --exec $DAEMON --test > /dev/null || return 1
+    start-stop-daemon --start -b --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS || return 2
+    # Add code here, if necessary, that waits for the process to be ready
+    # to handle requests from services started subsequently which depend
+    # on this one.  As a last resort, sleep for some time.
+}
 
-function stop() {
+#
+# Function that stops the daemon/service
+#
+do_stop(){
     validateStop
-    echo -n "Shutting down $NAME: "
-    killproc -p $PIDFILE $NAME
-    local exit_status=$?
-    echo
-    rm -f $LOCKFILE
-    return $exit_status
-}
-
-function restart(){
-    validateRestart
-    stop
-    sleep 1
-    start
-}
-
-function getStatus(){
-    status -p $PIDFILE $NAME -l $LOCKFILE
-}
-
-function solveDependency(){
-    local port="$1"
-    local count=0
-    #echo "${SPACES}      > Starting ingestion-${PORTS_CONFIG[$port]}"
-    # Start service dependency or die trying
-    service ingestion-${PORTS_CONFIG[$port]} start BLANK_SPACE=$[ $INDENT_LEVEL + 1 ] || \
-        ( echo "ERROR! Check service logs" ; exit 1 ; )
-}
-
-# Check the status of the services on which this one depends
-function checkDependencies(){
-    local failed
-    local port
-    local count=0
-    local exit_on_fail=""
-    local solve_dependencies=""
-    
-    # ARGS processing
-    while [ $# -gt 0 ]; do
-        case $1 in
-            exit_on_fail)       exit_on_fail="$1" ; shift ;;
-            solve_dependencies) solve_dependencies="$1" ; shift ;;
-            *)                  shift ;;
-        esac
-    done
-
-    if [ -n "$INDENT_LEVEL" ]; then
-        echo -n "${SPACES}      > Checking dependencies: "
-    else
-        echo -n "Checking service dependencies: "
-    fi
-    if [ "${#DEPENDENCIES}" -eq 0 ]; then
-        echo "none found"
-        return 0
-    fi
-    echo
-    for dep in $DEPENDENCIES; do
-    	local port=${CONFIG_PORTS[$dep]}
-        if [ -n "$INDENT_LEVEL" ]; then
-            echo -n "${SPACES}      - ingestion-$dep"
-        else
-            echo -n "   - ingestion-$dep"
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    RETVAL=0
+    if [ -f "$PIDFILE" ]; then
+        start-stop-daemon --stop --pidfile "$PIDFILE" --user "$USER" --quiet --retry=TERM/20/KILL/5 #--name $NAME
+        RETVAL="$?"
+        if [ "$RETVAL" -eq 1 ]; then
+                log_progress_msg "$DESC is not running but pid file exists, cleaning up"
+        elif [ "$RETVAL" -eq 3 ]; then
+                PID="$(cat $PIDFILE)"
+                log_failure_msg "Failed to stop $DESC (pid $PID)"
+                exit 1
         fi
-        # Only check dependencies
-        if [ ! "$solve_dependencies" ]; then
-            if  ! checkPort "$port"; then
-                echo " not available"
-                failed="yes"
-                if [ "$exit_on_fail" ]; then
-                    return 2
-                fi
-            else
-                echo_success
-                echo
-            fi
-        # Check & solve dependencies
-        else
-            if ! checkPort "$port"; then
-                echo " not available, starting up..."
-                solveDependency "$port"
-                echo -n "${SPACES}         > Checking ingestion-$dep"
-                while ! checkPort "$port"; do
-                    sleep $SLEEP_TIME
-                    echo -n "."
-                    let count=count+1
-                    if [ $count -gt $MAX_TRIES ]; then
-                        break="yes"
-                        break
-                    fi
-                done
-                if [ "$break" ]; then
-                    echo_failure
-                    echo " FAILED! Maximum retries reached!"
-                    return 1
-                else
-                    echo_success
-                    echo
-                fi
-            else
-                echo_success
-                echo
-            fi
-        fi
-        count=0
-    done
-    if [ "$failed" ]; then
-        return 1
+        rm -f "$PIDFILE"
     else
-        return 0
+        log_progress_msg "(not running)"
     fi
+    [ "$RETVAL" = 2 ] && return 2
+
+    # Wait for children to finish too if this is a daemon that forks
+    # and if the daemon is only ever run from this initscript.
+    # If the above conditions are not satisfied then add some other code
+    # that waits for the process to drop all resources that could be
+    # needed by services started subsequently.  A last resort is to
+    # sleep for some time.
+    #start-stop-daemon --stop --quiet --oknodo --retry=0/20/KILL/5 --exec $DAEMON
+    #[ "$?" = 2 ] && return 2
+
+    # Many daemons don't delete their pidfiles when they exit.
+    rm -f "$PIDFILE"
+    return "$RETVAL"
 }
 
-function usage(){
-    echo "Usage: $NAME {start|stop|status|restart|reload|force-reload|condrestart}"
-    exit 1
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+#do_reload() {
+#    #
+#    # If the daemon can reload its configuration without
+#    # restarting (for example, when it is sent a SIGHUP),
+#    # then implement that here.
+#    #
+#    #start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+#}
+
+# Remove global temp files upon exit
+function cleanup(){
+    if [ "$CREATED_LOCKFILE" ]; then rm -f "$LOCKFILE" ; fi
 }
+trap cleanup 0 # that's why there's no local temp files ;)
+
 # Tweak for pretty print stdout
 if [[ "$2" =~ BLANK_SPACE ]]; then
     INDENT_LEVEL="$(echo $2 | cut -d '=' -f2)"
@@ -240,13 +189,88 @@ if [[ "$2" =~ BLANK_SPACE ]]; then
     unset ARG
 fi
 
-# MAIN EXECUTION
 case "$1" in
-    start)                          start ;;
-    stop)                           stop ;;
-    status)                         getStatus ;;
-    restart|reload|force-reload)    restart ;;
-    check)                          checkDependencies;;
-    *)                              usage ;;
+  start)
+    if [ -n "$INDENT_LEVEL" ]; then
+        echo -n "${SPACES}      > Starting $NAME: "
+    else
+        echo -n "Starting $NAME: "
+    fi
+    if status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" > /dev/null 2>&1; then
+        echo -n "already running"
+    fi
+    #log_daemon_msg "Starting $DESC" "$NAME"
+    do_start
+    case "$?" in
+        0|1) log_end_msg 0 ;;
+        2) log_end_msg 1 ;;
+    esac
+    ;;
+  stop)
+    #log_daemon_msg "Stopping $DESC" "$NAME"
+    echo -n "Shutting down $NAME: "
+    do_stop
+    case "$?" in
+        0|1) log_end_msg 0 ;;
+        2) log_end_msg 1 ;;
+    esac
+    ;;
+  status)
+    status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
+    ;;
+  #reload|force-reload)
+    #
+    # If do_reload() is not implemented then leave this commented out
+    # and leave 'force-reload' as an alias for 'restart'.
+    #
+    #log_daemon_msg "Reloading $DESC" "$NAME"
+    #do_reload
+    #log_end_msg $?
+    #;;
+  restart|reload|force-reload)
+    #
+    # If the "reload" option is implemented then remove the
+    # 'force-reload' alias
+    #
+    validateRestart
+    #log_daemon_msg "Restarting $DESC" "$NAME"
+    echo -n "Shutting down $NAME: "
+    do_stop
+    case "$?" in
+        0|1) log_end_msg 0 ;;
+        2) log_end_msg 1 ;;
+    esac
+    # Need to delete LOCKFILE so start doesn't get stuck
+    rm -f "$LOCKFILE"
+    case "$?" in
+      0|1)
+        if [ -n "$INDENT_LEVEL" ]; then
+            echo -n "${SPACES}      > Starting $NAME: "
+        else
+            echo -n "Starting $NAME: "
+        fi
+        if status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" > /dev/null 2>&1; then
+            echo -n "already running"
+        fi
+        do_start
+        case "$?" in
+            0) log_end_msg 0 ;;
+            1) log_end_msg 1 ;; # Old process is still running
+            *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+        ;;
+    esac
+    ;;
+  check)
+    checkDependencies;;
+  *)
+    echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|force-reload|check}" >&2
+    exit 3
+    ;;
 esac
-exit $?
+
+exit 0
